# base config
agent: 'MHGNNKGE' # GAT, MHGNN, MPNN, DDQN
seed: 42
logger: 'wandb' # options: 'wandb', 'tensorboard', 'swanlab'
project_name: "satNetEnv3"
wandb_user_name: "wmqbit"
log_dir: 'logs'
model_dir: 'models' # 前面不要加 / ./ 等

device: "cuda:0"

# environment parameters
n_order_adj: 4 # number of order for adjacency matrix
action_size: 4 # number of possible actions
input_dim: 10 # dimension of input each node features

# training parameters
train_TA_model: true # whether to train the teacher agent network
use_student_network: false # whether to use the student network for action selection

mode_load_dir: "SimResults/GAT/2025-12-24/22-20-31_Starlink_3s_GTs_[4]/"
outputPath: '/home/wmq/Desktop/MA-DRL_Routing_Simulator-main/SimResults/MHGNNKGE/2026-01-10/19-19-11_Starlink_3s_GTs_[4]/train/'
CurrentGTnumber: 4
